import { requireUser, sameOrigin } from '../../../_lib/auth.js';
const H={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const HOSTS=new Set(['www.ris.bka.gv.at','ris.bka.gv.at','ogd.ris.bka.gv.at']);
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const norm=x=>String(x??'').normalize('NFC').replace(/\u00a0/g,' ').replace(/[\t ]+/g,' ').replace(/\s*\n\s*/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
function snapshot(x){try{const s=JSON.parse(x);return s?.provisions?s:null}catch{return null}}
function urlOf(x){const value=x?.documentUrl||x?.metadata?.documentUrl||'';try{const u=new URL(value,'https://www.ris.bka.gv.at');return u.protocol==='https:'&&HOSTS.has(u.hostname.toLowerCase())?u.href:''}catch{return ''}}
function htmlText(x){return norm(String(x||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(p|div|li|tr|h[1-6]|section|article)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"'))}
async function loadText(url){if(!url)return null;const r=await fetch(url,{headers:{Accept:'text/html,application/xhtml+xml,application/xml;q=0.9,text/plain;q=0.8'}});if(!r.ok)throw Error('RIS-Dokument nicht abrufbar: HTTP '+r.status);const raw=await r.text(),type=r.headers.get('content-type')||'';return (/html|xml/i.test(type)||/<[^>]+>/.test(raw.slice(0,500))?htmlText(raw):norm(raw)).slice(0,180000)}
function diff(a,b){const old=a.provisions||{},cur=b.provisions||{},keys=[...new Set([...Object.keys(old),...Object.keys(cur)])].sort((x,y)=>x.localeCompare(y,'de-AT'));return keys.flatMap(key=>{const p=old[key],n=cur[key];if(!p&&n)return[{type:'added',key,p:null,n}];if(p&&!n)return[{type:'removed',key,p,n:null}];if(p?.hash!==n?.hash)return[{type:'modified',key,p,n}];return[]})}
export async function onRequestPost({request,env}){
 if(!sameOrigin(request))return out({error:'Ungültiger Ursprung.'},403);const auth=await requireUser(request,env);if(auth.error)return auth.error;if(!env.COLLECTIONS_DB)return out({error:'D1-Binding COLLECTIONS_DB fehlt.'},503);
 let body;try{body=await request.json()}catch{return out({error:'Ungültiges JSON.'},400)}const collectionId=String(body?.collectionId||'').trim(),lawId=String(body?.lawId||'').trim();if(!collectionId||!lawId)return out({error:'Sammlung und Vorschrift fehlen.'},400);const db=env.COLLECTIONS_DB,userId=auth.me?.id;
 try{const law=await db.prepare(`SELECT rl.id,rl.title,rl.ris_number,rl.ris_url,pc.name collection_name FROM personal_collection_laws pcl JOIN personal_collections pc ON pc.id=pcl.collection_id AND pc.user_id=pcl.user_id JOIN ris_laws rl ON rl.id=pcl.law_id WHERE pcl.user_id=? AND pcl.collection_id=? AND pcl.law_id=? LIMIT 1`).bind(userId,collectionId,lawId).first();if(!law)return out({error:'Vorschrift wurde in dieser Sammlung nicht gefunden.'},404);
 const q=await db.prepare(`SELECT snapshot_json,created_at FROM personal_law_snapshots WHERE user_id=? AND collection_id=? AND law_id=? ORDER BY created_at DESC,rowid DESC LIMIT 2`).bind(userId,collectionId,lawId).all(),rows=q.results||[];if(rows.length<2)return out({error:'Für den Alt-Neu-Vergleich werden zwei erfolgreiche RIS-Prüfstände benötigt.'},409);const current=snapshot(rows[0].snapshot_json),previous=snapshot(rows[1].snapshot_json);if(!current||!previous)return out({error:'Ein gespeicherter Prüfsnapshot ist nicht lesbar.'},422);
 const all=diff(previous,current),selected=all.slice(0,10),changes=[];for(const d of selected){const previousUrl=urlOf(d.p),currentUrl=urlOf(d.n);let previousText=norm(d.p?.text)||null,currentText=norm(d.n?.text)||null,warning=null;try{if(!previousText&&previousUrl)previousText=await loadText(previousUrl);if(!currentText&&currentUrl)currentText=await loadText(currentUrl)}catch(e){warning=String(e.message||e)}changes.push({type:d.type,provisionKey:d.key,provisionTitle:norm(d.n?.title||d.p?.title||d.key),previousText,currentText,previousUrl:previousUrl||null,currentUrl:currentUrl||null,warning})}
 return out({law:{id:law.id,title:norm(law.title),risNumber:law.ris_number,risUrl:law.ris_url,collectionName:law.collection_name},previousCheckedAt:rows[1].created_at,currentCheckedAt:rows[0].created_at,totalChanges:all.length,comparedChanges:changes.length,truncated:all.length>changes.length,changes});
 }catch(e){console.error('Alt-Neu-Vergleich:',e);return out({error:'Alt-Neu-Vergleich konnte nicht ausgeführt werden.'},503)}
}
